
all:
	cd libir2; make
	make -f makefile.dv

clean:
	cd libir2; make clean
	make -f makefile.dv clean

realclean:
	cd libir2; make realclean
	make -f makefile.dv realclean

install:
	make -f makefile.dv install
